let chart, raceData;
let currentLang = localStorage.getItem("emu6Lang") || "hu";
const $ = id => document.getElementById(id);
const colors = ["#38bdf8","#f472b6","#a78bfa","#34d399","#fbbf24","#fb7185","#60a5fa","#c084fc","#2dd4bf","#f97316","#4ade80","#e879f9","#22d3ee","#facc15","#818cf8","#fb923c","#4ade80","#f43f5e"];
const translations = {
  hu:{eyebrow:"XV. EMU 6-Day Race / GOMU 6-Day World Championship",title:"Live Race Analyzer",eventInfo:"Balatonfüred · 144H · 1 kör = 898,2 m",promoTitle:"Játssz a fotóiddal! – Photawesome",promoText:"Fotós játék és közösségi oldal, ahol a fényképezésből játék lesz.",promoButton:"Megnézem →",searchLabel:"Versenyző keresése",searchPlaceholder:"Név vagy rajtszám…",displayLabel:"Megjelenítés",top10:"Top 10",top20:"Top 20",top50:"Top 50",top100:"Top 100",everyone:"Mindenki",hungarians:"Csak magyarok",reset:"Szűrők törlése",chartTitle:"Megtett táv az idő függvényében",chartSubtitle:"A vízszintes szakaszok pihenést/állást jeleznek.",legendNote:"Kattints egy névre a ki-/bekapcsoláshoz.",timeRangeLabel:"Időintervallum",last24:"Utolsó 24 óra",fullRace:"Teljes verseny",customRange:"Egyéni időszak",rangeStart:"Kezdete",rangeEnd:"Vége",apply:"Alkalmaz",rankingTitle:"Aktuális állás",rank:"#",athlete:"Versenyző",country:"Ország",category:"Kategória",laps:"Kör",km:"Km",lastLap:"Utolsó kör",source:"Adatforrás: Köridő",updated:"frissítve",noUpdate:"nincs frissítési idő"},
  en:{eyebrow:"XV. EMU 6-Day Race / GOMU 6-Day World Championship",title:"Live Race Analyzer",eventInfo:"Balatonfüred · 144H · 1 lap = 898.2 m",promoTitle:"Play with your photos! – Photawesome",promoText:"A photo game and community where photography becomes a game.",promoButton:"Visit →",searchLabel:"Search athlete",searchPlaceholder:"Name or bib number…",displayLabel:"Display",top10:"Top 10",top20:"Top 20",top50:"Top 50",top100:"Top 100",everyone:"Everyone",hungarians:"Hungarians only",reset:"Clear filters",chartTitle:"Distance over time",chartSubtitle:"Horizontal sections indicate rest/stationary periods.",legendNote:"Click a name to show/hide the athlete.",timeRangeLabel:"Time range",last24:"Last 24 hours",fullRace:"Full race",customRange:"Custom range",rangeStart:"Start",rangeEnd:"End",apply:"Apply",rankingTitle:"Current standings",rank:"#",athlete:"Athlete",country:"Country",category:"Category",laps:"Laps",km:"Km",lastLap:"Last lap",source:"Data source: Köridő",updated:"updated",noUpdate:"no update time"}
};
function t(key){return translations[currentLang][key]||translations.hu[key]||key;}
function formatDate(date){return new Date(date).toLocaleString(currentLang==="hu"?"hu-HU":"en-GB");}
function applyLanguage(){document.documentElement.lang=currentLang;document.querySelectorAll("[data-i18n]").forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll("[data-i18n-placeholder]").forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));document.querySelectorAll(".lang-btn").forEach(btn=>btn.classList.toggle("active",btn.dataset.lang===currentLang));if(raceData)render();}
async function load(){const r=await fetch("data/race.json?ts="+Date.now(),{cache:"no-store"});if(!r.ok)throw new Error("A race.json nem tölthető be.");raceData=await r.json();initializeTimeRange();applyLanguage();updateCustomRangeVisibility();}
function countryCode(value){return String(value??"").trim().toUpperCase().substring(0,3);}
function isHungarian(value){const country=String(value??"").trim().toUpperCase();return country==="HUN"||country.startsWith("HUN_")||country.startsWith("HUN-");}
function filteredAthletes(){const search=$("search").value.trim().toLowerCase(),hu=$("hungarians").checked;let a=raceData.athletes.filter(x=>{const ms=!search||String(x.name??"").toLowerCase().includes(search)||String(x.bib??"").includes(search);return ms&&(!hu||isHungarian(x.country));});a.sort((x,y)=>Number(y.km)-Number(x.km));const limit=Number($("limit").value);return limit?a.slice(0,limit):a;}
function getAllTimes(){return raceData.athletes.flatMap(a=>(a.points||[]).map(p=>new Date(p.t).getTime())).filter(Number.isFinite);}
function initializeTimeRange(){const times=getAllTimes();if(!times.length)return;$("rangeStart").value=toDateTimeLocal(new Date(Math.min(...times)));$("rangeEnd").value=toDateTimeLocal(new Date(Math.max(...times)));}
function toDateTimeLocal(date){const pad=n=>String(n).padStart(2,"0");return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;}
function updateCustomRangeVisibility(){const custom=$("timeRange").value==="custom";$("customRange").hidden=!custom;$("customRange").setAttribute("aria-hidden",String(!custom));}
function getChartRange(){const mode=$("timeRange").value,times=getAllTimes();if(!times.length)return{};const minTime=Math.min(...times),maxTime=Math.max(...times);if(mode==="full")return{min:minTime,max:maxTime};if(mode==="24h")return{min:Math.max(minTime,maxTime-24*60*60*1000),max:maxTime};const start=new Date($("rangeStart").value).getTime(),end=new Date($("rangeEnd").value).getTime();if(!Number.isFinite(start)||!Number.isFinite(end)||start>=end)return{};return{min:start,max:end};}
function render(){const athletes=filteredAthletes();drawChart(athletes);drawTable(athletes);$("status").textContent=`${raceData.athletes.length} ${currentLang==="hu"?"versenyző":"athletes"} · ${raceData.updatedAt?t("updated")+" "+formatDate(raceData.updatedAt):t("noUpdate")}`;$("updated").textContent=raceData.updatedAt?`${t("updated")}: ${formatDate(raceData.updatedAt)}`:"";}
function drawChart(athletes){const ctx=$("raceChart").getContext("2d");if(chart)chart.destroy();const datasets=athletes.map((a,i)=>({label:a.name,data:a.points,parsing:{xAxisKey:"t",yAxisKey:"km"},borderColor:colors[i%colors.length],backgroundColor:colors[i%colors.length],borderWidth:i<5?2.7:1.5,pointRadius:0,pointHitRadius:8,tension:0,spanGaps:true}));const range=getChartRange();chart=new Chart(ctx,{type:"line",data:{datasets},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:"nearest",intersect:false},plugins:{legend:{position:"bottom",labels:{color:"#cbd5e1",usePointStyle:true,padding:14}},tooltip:{callbacks:{title:items=>items[0]?.raw?formatDate(items[0].raw.t):"",label:item=>`${item.dataset.label}: ${Number(item.raw.km).toFixed(1)} km`}}},scales:{x:{type:"time",min:range.min,max:range.max,time:{unit:"hour",displayFormats:{hour:currentLang==="hu"?"d. HH:mm":"MMM d, HH:mm"}},ticks:{color:"#94a3b8"},grid:{color:"#1f2b40"},title:{display:true,text:currentLang==="hu"?"Idő":"Time",color:"#94a3b8"}},y:{beginAtZero:true,ticks:{color:"#94a3b8",callback:v=>v+" km"},grid:{color:"#1f2b40"},title:{display:true,text:currentLang==="hu"?"Megtett táv":"Distance",color:"#94a3b8"}}}}});}
if(!window._adapterLoaded){window._adapterLoaded=true;const s=document.createElement("script");s.src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns@3.0.0/dist/chartjs-adapter-date-fns.bundle.min.js";s.onload=load;document.head.appendChild(s);}else load();
function drawTable(athletes){$("ranking").innerHTML=athletes.map((a,i)=>`<tr><td>${i+1}</td><td><strong>${escapeHtml(a.name)}</strong> <span class="muted">#${a.bib}</span></td><td>${escapeHtml(countryCode(a.country))}</td><td>${escapeHtml(a.category||"")}</td><td>${a.laps}</td><td>${Number(a.km).toFixed(3)}</td><td>${escapeHtml(a.lastLap||"")}</td></tr>`).join("");}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));}
$("search").addEventListener("input",render);$("limit").addEventListener("change",render);$("hungarians").addEventListener("change",render);$("timeRange").addEventListener("change",()=>{updateCustomRangeVisibility();render();});$("applyRange").addEventListener("click",render);$("reset").addEventListener("click",()=>{$("search").value="";$("limit").value="20";$("hungarians").checked=false;$("timeRange").value="24h";updateCustomRangeVisibility();initializeTimeRange();render();});document.querySelectorAll(".lang-btn").forEach(btn=>btn.addEventListener("click",()=>{currentLang=btn.dataset.lang;localStorage.setItem("emu6Lang",currentLang);applyLanguage();}));
