import os, re, json, time
from datetime import datetime, timezone
from concurrent.futures import ThreadPoolExecutor, as_completed
import requests
from bs4 import BeautifulSoup

BASE = "https://korido.hu"
RESULT = BASE + "/2026EMU6_result?team=1"
LAP_URL = BASE + "/events/resultTableLaps.php?bib={bib}&rc=3600"
MAX_ATHLETES = int(os.getenv("MAX_ATHLETES", "0"))  # 0 = all
WORKERS = int(os.getenv("WORKERS", "8"))

session = requests.Session()
session.headers.update({"User-Agent":"Mozilla/5.0 EMU-6-Day-Race-Analyzer/1.0"})

def text(el):
    return " ".join(el.stripped_strings) if el else ""

def parse_main(html):
    soup = BeautifulSoup(html, "html.parser")
    athletes = []
    seen = set()
    for a in soup.find_all("a", href=True):
        m = re.search(r"resultTableLaps\.php\?bib=(\d+)", a["href"])
        if not m:
            continue
        bib = int(m.group(1))
        if bib in seen:
            continue
        seen.add(bib)
        row = a.find_parent("tr")
        cells = row.find_all("td") if row else []
        vals = [text(c) for c in cells]
        # Main result table columns: pos, category pos, bib, name, country, category, lap, km, last lap, last lap time
        country = vals[4] if len(vals) > 4 else ""
        category = vals[5] if len(vals) > 5 else ""
        athletes.append({"bib":bib, "name":text(a), "country":country, "category":category})
    # Fallback: parse table rows if links are generated by JS.
    if not athletes:
        for row in soup.find_all("tr"):
            cells = [text(c) for c in row.find_all(["td","th"])]
            if len(cells) >= 8 and cells[0].isdigit() and cells[2].isdigit():
                athletes.append({"bib":int(cells[2]),"name":cells[3],"country":cells[4],"category":cells[5]})
    return athletes

def parse_laps(bib):
    r = session.get(LAP_URL.format(bib=bib), timeout=30)
    r.raise_for_status()
    soup = BeautifulSoup(r.text, "html.parser")
    rows = []
    table = soup.find("table")
    if not table:
        return None
    for tr in table.find_all("tr"):
        cells = [text(c) for c in tr.find_all(["td","th"])]
        if len(cells) < 6 or not cells[0].isdigit():
            continue
        lap = int(cells[0])
        km = float(cells[1].replace(",", "."))
        lap_time = cells[2]
        read_time = cells[5]
        try:
            dt = datetime.strptime(read_time, "%Y.%m.%d %H:%M:%S").replace(tzinfo=timezone.utc)
        except ValueError:
            continue
        rows.append({"lap":lap,"km":km,"lapTime":lap_time,"readTime":dt.isoformat()})
    return rows

def main():
    html = session.get(RESULT, timeout=30).text
    athletes = parse_main(html)
    athletes.sort(key=lambda x:x["bib"])
    if MAX_ATHLETES:
        # Prefer current ranking order from the page, which is the order returned above.
        athletes = athletes[:MAX_ATHLETES]
    out = []
    with ThreadPoolExecutor(max_workers=WORKERS) as ex:
        futures = {ex.submit(parse_laps,a["bib"]):a for a in athletes}
        for f in as_completed(futures):
            a = futures[f]
            try:
                laps = f.result()
                if not laps:
                    continue
                points = [{"t":x["readTime"],"km":x["km"]} for x in laps]
                last = laps[-1]
                a.update({
                    "laps":len(laps),
                    "km":last["km"],
                    "lastLap":last["lapTime"],
                    "lastReadTime":last["readTime"],
                    "points":points
                })
                out.append(a)
            except Exception as e:
                print(f"bib {a['bib']} failed: {e}")
    out.sort(key=lambda x:x["km"], reverse=True)
    data = {
        "event":"XV. EMU 6-Day Race / GOMU 6-Day World Championship",
        "lapKm":0.8982,
        "updatedAt":datetime.now(timezone.utc).isoformat(),
        "athletes":out
    }
    os.makedirs("data", exist_ok=True)
    with open("data/race.json","w",encoding="utf-8") as f:
        json.dump(data,f,ensure_ascii=False,separators=(",",":"))
    print(f"Wrote {len(out)} athletes")

if __name__ == "__main__":
    main()
